config/routes.rb
Tradr::Application.routes.draw do
    root :to => 'home#index'
  resources :users, :only => [:index, :new, :create]
  resources :stocks, :only => [:index, :new, :create] do
    collection do
      get '/charts/:charts', :action => 'chart'
    end
  end

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

end

app/models/stock.rb
# == Schema Information
#
# Table name: stocks
#
#  id             :integer          not null, primary key
#  symbol         :string(255)
#  shares         :integer
#  purchase_price :decimal(, )
#  user_id        :integer
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#

class Stock < ActiveRecord::Base
  attr_accessible :symbol, :shares, :purchase_price
  belongs_to :user, :inverse_of => :stocks

  def Stock.quote(symbol)
    symbol = symbol.upcase
    YahooFinance::get_quotes(YahooFinance::StandardQuote, symbol)[symbol].lastTrade
  end

  before_save :upcase_symbol, :get_purchase_price
  private
  def upcase_symbol
    self.symbol = self.symbol.upcase
  end

  def get_purchase_price
    self.purchase_price = Stock.quote(self.symbol)
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  email           :string(255)
#  password_digest :string(255)
#  balance         :decimal(, )
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ActiveRecord::Base
  has_secure_password
  attr_accessible :email, :balance, :password, :password_confirmation
  has_many :stocks, :inverse_of => :user

  def position
    self.stocks.map{|s| Stock.quote(s.symbol) * s.shares}.reduce(:+) || 0
  end

  def total
    self.position + self.balance
  end

  def purchase(symbol, shares)
    symbol = symbol.upcase
    stock = Stock.where(:symbol => symbol).first || Stock.new(:symbol => symbol, :shares => 0)
    stock.shares += (shares.to_i)
    stock.save
    self.stocks << stock if self.stocks.exclude?(stock)
    self.balance -= Stock.quote(symbol) * (shares.to_i)
    self.save
  end

  def has_enough_money?(symbol, shares) #returns a true or false
    symbol = symbol.upcase
    quote = Stock.quote(symbol)
    (quote * shares.to_i) <= self.balance
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authenticate

  private
  def authenticate
      return unless session[:user_id]
      @auth = User.find(session[:user_id])

      unless @auth
        session[:user_id] = nil
        redirect_to :root_url
    end
  end
end

app/controllers/home_controller.rb
class HomeController <ApplicationController
  def index
    @users = User.all
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController

  def new
  end

  def create
    user = User.where(:email => params[:email]).first
    if  user.present? && user.authenticate(params[:password])
        session[:user_id] = user.id
        redirect_to(root_path)
    else
        redirect_to(login_path)
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to(root_path)
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  before_filter :only_authorized

  def index
    # @stocks = @auth.stocks.order(:activity).order(:completed)
    @stocks = @auth.stocks.uniq.sort
    @stock = Stock.new
  end

  def chart
    symbols = params[:charts]

    result = YahooFinance::get_HistoricalQuotes_days( symbols, 30 )

    render :json => result
  end

  # def new
  #   @stock = Stock.new
  # end


  def create
    if @auth.has_enough_money?(params[:stock][:symbol], params[:stock][:shares])
       @auth.purchase(params[:stock][:symbol], params[:stock][:shares])

       @stocks = @auth.stocks


  end
end




  private

    def only_authorized
      redirect_to(root_path) if @auth.nil?
    end




 end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end


  def new
    @user = User.new
  end



  def create
    User.create(params[:user])
    @users = User.order(:email)
    respond_to do |format|
      format.html {redirect_to(users_path)} #it can handle the html case
      format.js {render :create}  #javascript is fine goest o find create.js so it goes to the create.js file
    end
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
  def login_nav
    if @auth.present?
        link_to(@auth.email, login_path, :method => :delete, :class => 'btn btn-large')
      else
        link_to('Login', login_path, :class => 'btn btn-danger')
      end
    end


  def user_logged_in_nav
    if @auth.present?
      button_tag(number_to_currency(@auth.balance), :class => 'btn btn-large', :id => 'update_balance')
    end
  end
end

app/views/home/index.html.haml
Lose all your money with Tradr

app/views/layouts/_body.html.erb
<div class="row">
  <div class="span12">
    <%= yield %>
  </div>
  </div>

app/views/layouts/_footer.html.haml
.footer.navbar-fixed-bottom
  %p.pull-left
    = link_to 'Home',  root_path
    | #{link_to 'Users',  users_path}

app/views/layouts/_nav.html.haml
.navbar.navbar-fixed-top
  .navbar-inner
    .container
      .nav-collapse
        %ul.nav
          %li.link= link_to 'Home',  root_path
          %li.link= link_to 'Users', users_path
          %li.link= link_to 'Stocks', stocks_path
          %li.navright= login_nav
          %li= user_logged_in_nav
      .nav.pull-right
        %h2
          TRADR

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
    <meta charset="utf-8" />

    <!-- Uncomment to make IE8 render like IE7 -->
    <!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

    <!-- Set the viewport width to device width for mobile -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>TRADR</title>

    <%= stylesheet_link_tag "application" %>
    <link rel="stylesheet" href="http://cdn.oesmith.co.uk/morris-0.4.3.min.css">
    <%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= javascript_include_tag "application" %>
    <script src="//cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
    <script src="http://cdn.oesmith.co.uk/morris-0.4.3.min.js"></script>
    <%= csrf_meta_tags %>
  </head>

  <body>

  <%= render :partial => 'layouts/nav' %>
  <div class="box">
  <%= render :partial => 'layouts/body' %>
</div>
  <%= render :partial => 'layouts/footer' %>

  </body>
</html>

app/views/session/new.html.haml
%div.container
  %div.large-3.columns
    = form_tag '/login' do
      = label_tag :email
      = text_field_tag :email, nil, :autofocuse => true
      = label_tag :password
      = password_field_tag :password
      = submit_tag 'Login', :class => 'button radius'
  %div.large-9.columns

app/views/stocks/_form.html.haml
%div.buy
  = form_for @stock, :remote => true do |f|
    = f.label :symbol
    = f.text_field :symbol, :autofocus => true
    = f.label :shares
    = f.number_field :shares
    = link_to('Cancel', '#', :id => 'cancel_stock_form', :class => 'btn btn-danger')
    = f.submit 'Buy Stock',  :class => 'btn btn-success'

app/views/stocks/_stocks.html.haml
%div.row
- @stocks.each do |stock|
  %div.span2
    %ul
      %li= check_box_tag(stock.symbol, '', false, :class => 'show_chart')
      %li= stock.symbol.upcase
      %li= stock.shares

app/views/stocks/create.js.erb
$('form')[0].reset();
//debugger;
$('#stocks').html('<%=j render(:partial => 'stocks') %>'); //repopulate the users with the users data
$('#update_balance').html('<%=@auth.balance  %>');

app/views/stocks/index.html.haml
%div#buy
  = render(:partial => 'form')


  %ol#stocks
    = render(:partial => 'stocks')



%div#chart
  - @auth.stocks.each do |stock|
    %div{ :id=>"chart_#{stock.symbol}" }

app/views/users/_form.html.haml
%div.container
  %div.section
    = form_for @user, :remote => true do |f|
      = f.label :email
      = f.text_field :email, :autofocus => true
      = f.label :password
      = f.password_field :password
      = f.label :password_confirmation
      = f.password_field :password_confirmation
      = f.label :balance
      = f.text_field :balance
      = f.submit 'Create your Account', :class => 'btn btn-success'

app/views/users/_users.html.haml
%h2 Current Users
- @users.each do |user|
  %p
    = user.email
    = number_to_currency user.balance

app/views/users/create.js.erb
$('#new_user').fadeOut(function () {
  $(this).empty().show();
});

$('#users').html('<%=j render(:partial => 'users') %>'); //repopulate the users with the users data

//tells how browsser to handle
//empty the form, on line 5 select the users class from the index html page  and replace its html with the users list

app/views/users/index.html.haml
= link_to('Add', new_user_path, :remote => true, :class => 'btn btn-danger')

%div#new_user

%ol#users
  = render(:partial => 'users/users')

app/views/users/new.html.haml
%h3  New User
= render(:partial => 'form')
//populates the page, called by the javascript

app/views/users/new.js.erb
$('#new_user').html('<%=j render(:partial => 'form') %>'); //select the new user empty div on the index page, and replace empty html with the html from the form partial html